{
 "title": "Web Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "tid", "label": "Tracking ID", "query": "label_values(tid)" },
   { "name": "event", "label": "Event type", "query": "label_values(type)" }
  ]
 },
 "panels": [
  {
   "title": "Views",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "﻿sum(count_over_time({type=~\"$event\", tid=\"$tid\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "﻿sum(count_over_time({type=~\"$event\", tid=\"$tid\"}[$__interval]))",
     "legendFormat": "Page views"
    },
    {
     "expr": "﻿sum(count_over_time({type=~\"$event\", tid=\"$tid\"} |~  `\"new_visitor\":true` [$__interval]))",
     "legendFormat": "New visitors"
    }
   ]
  },
  {
   "title": "Visits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "﻿sum(count_over_time({type=~\"$event\", tid=\"$tid\"}[$__interval]))",
     "legendFormat": "Page views"
    },
    {
     "expr": "﻿sum(count_over_time({type=~\"$event\", tid=\"$tid\"} |~  `\"new_visitor\":true` [$__interval]))",
     "legendFormat": "New visitors"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({type=~\"$event\", tid=\"$tid\"} | json [$__interval])) by (country)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "﻿sum(count_over_time({type=~\"$event\", tid=\"$tid\"} |~  `\"new_visitor\":true` [$__interval]))"
    }
   ]
  },
  {
   "title": "Top browser",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (browser) (count_over_time({type=~\"$event\", tid=\"$tid\"} | json [$__interval]))",
     "legendFormat": "{{browser}}"
    }
   ]
  },
  {
   "title": "Top OS",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (os) (count_over_time({type=~\"$event\", tid=\"$tid\"} | json [$__interval]))",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "Top Country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (country) (count_over_time({type=~\"$event\", tid=\"$tid\"} | json [$__interval]))",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Top pages",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (path) (count_over_time({type=~\"$event\", tid=\"$tid\"} | json [$__interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top referers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "topk(5,sum(count_over_time({type=~\"$event\", tid=\"$tid\"} | json | referer != \"\" [$__interval])) by (referer))",
     "legendFormat": "{{referer}}"
    }
   ]
  }
 ]
}